version: "3.9"
name: dr
services:
  dr:
    image: ghcr.io/savand/dyvo-ranok-be/dyvo-ranok-be:latest
    container_name: dr
    ports:
      - target: 8080
        published: 8080
    environment:
      - TZ=Europe/Kyiv
      - JAVA_TOOL_OPTIONS=-Xmx256m -Xms256m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/dump
      - SPRING_CONFIG_LOCATION=file:///appconfig/application.yml
#      - G_API_KEY=
#      - RECAPTCHA_SITE_KEY=
#      - SMTP_PASS=
    volumes:
      - ~/dr/logs:/logs
      - ~/dr/config/application.yml:/appconfig/application.yml
      - ~/dr/dump:/dump
